AllCops:
  Exclude:
    - 'audit_reports/**/*'
    - 'cache/**/*'
    - 'lambda/**/*'
  NewCops: enable
# Stuff I want more lax than the defaults
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Max: 40
# Stuff I don't want to worry about for now
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false